import {useEffect,useMemo,useState} from 'react';
import {Line,LineChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {EmptyState,ErrorState,FactBadge,LoadingState,MarketChange,Panel,SourceDisclosure,StatusBadge} from '@argus/design-system';
import {formatBasisPoints,formatTimestamp,formatYield} from '@argus/financial-formatting';
import {fetchDemoHome,fetchMarketSnapshot,isStale,type DemoHome,type MarketSnapshot} from './api';

const nav=[['⌂','Home'],['⌁','Pakistan Rates'],['▥','Macro'],['⇄','FX & Liquidity'],['◇','Auctions'],['◎','Global'],['≡','News'],['⌕','Explorer'],['ƒ','Analytics'],['▤','Journal'],['✦','Copilot'],['⚙','System']];
function Logo(){return <div className="brand"><span className="mark">A</span><div><b>ARGUS</b><small>MARKETS WORKSTATION</small></div></div>}
function Clock(){const [now,setNow]=useState(new Date());useEffect(()=>{const timer=setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(timer)},[]);const time=(zone:string)=>new Intl.DateTimeFormat('en-GB',{timeZone:zone,hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(now);return <div className="clock"><span><small>UTC</small><b>{time('UTC')}</b></span><span><small>PKT</small><b>{time('Asia/Karachi')}</b></span></div>}
function CommandPalette({close}:{close:()=>void}){return <div className="palette-wrap" onMouseDown={close}><div className="palette" role="dialog" aria-modal="true" aria-label="Command palette" onMouseDown={event=>event.stopPropagation()}><div className="palette-input"><span>⌕</span><input autoFocus placeholder="Search instruments, functions, or workspaces…"/><kbd>ESC</kbd></div><div className="palette-section">QUICK NAVIGATION</div>{nav.slice(0,6).map(([icon,label],index)=><button key={label}><span>{icon}&nbsp;&nbsp;{label}</span><kbd>0{index+1}</kbd></button>)}</div></div>}
function ShellState({kind,retry}:{kind:'loading'|'error'|'empty';retry:()=>void}){return <div className="shell-state">{kind==='loading'?<LoadingState/>:kind==='error'?<><ErrorState/><p>The local demo API could not be reached.</p><button onClick={retry}>Retry connection</button></>:<EmptyState label="Demo API returned no workspace data"/>}</div>}

export function App(){
  const [data,setData]=useState<DemoHome|null>(null);const [snapshot,setSnapshot]=useState<MarketSnapshot|null>(null);const [error,setError]=useState(false);const [request,setRequest]=useState(0);const [palette,setPalette]=useState(false);
  useEffect(()=>{const controller=new AbortController();Promise.all([fetchDemoHome(controller.signal),fetchMarketSnapshot(controller.signal)]).then(([demo,market])=>{setData(demo);setSnapshot(market)}).catch(e=>{if(e.name!=='AbortError')setError(true)});return()=>controller.abort()},[request]);
  useEffect(()=>{const key=(event:KeyboardEvent)=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='k'){event.preventDefault();setPalette(true)}if(event.key==='Escape')setPalette(false)};addEventListener('keydown',key);return()=>removeEventListener('keydown',key)},[]);
  const stale=useMemo(()=>data?isStale(data.generated_at,data.stale_after_seconds):false,[data]);
  const empty=!!data&&(!data.rates.length||!data.global_markets.length);
  return <div className="app">
    <header className="topbar"><Logo/><button className="search" onClick={()=>setPalette(true)} aria-label="Open command search"><span>⌕</span><span>Search markets or run a command</span><kbd>CTRL K</kbd></button><div className="sessions"><span><i/>PSX CLOSED</span><span><i className="open"/>LONDON OPEN</span><span><i/>US PRE</span></div><div className={`freshness ${stale?'stale':''}`}><i/>{stale?'STALE':'DEMO FRESH'}</div><Clock/></header>
    <aside><div className="nav-label">WORKSTATION</div>{nav.map(([icon,label],index)=><button className={index===0?'active':''} key={label}><span className="nav-icon">{icon}</span>{label}{index===0&&<span className="active-dot"/>}</button>)}<div className="sidebar-foot"><StatusBadge status="DEMO"/><span>Fixture environment<br/>No live market data</span></div></aside>
    <main><div className="workspace-head"><div><div className="breadcrumb">WORKSTATION / <b>HOME</b></div><h1>Pakistan Markets Monitor</h1></div><div className="workspace-actions"><span>DESKTOP · DEFAULT</span><button>▦ Layout</button><button>•••</button></div></div>
      <div className="demo-banner"><b>DEMO ENVIRONMENT</b><span>{data?.disclaimer??'Loading explicitly synthetic interface fixtures…'}</span><StatusBadge status="DEMO"/></div>
      {!data&&!error?<ShellState kind="loading" retry={()=>setRequest(x=>x+1)}/>:error?<ShellState kind="error" retry={()=>{setError(false);setData(null);setRequest(x=>x+1)}}/>:empty?<ShellState kind="empty" retry={()=>setRequest(x=>x+1)}/>:data&&<Workspace data={data} snapshot={snapshot} stale={stale}/>}
    </main>{palette&&<CommandPalette close={()=>setPalette(false)}/>}</div>
}

function Workspace({data,snapshot,stale}:{data:DemoHome;snapshot:MarketSnapshot|null;stale:boolean}){const curve=data.rates.map(rate=>({tenor:rate.tenor,yield:rate.yield_percent}));const spread=(data.rates.at(-1)!.yield_percent-data.rates[0].yield_percent)*100;const official=snapshot?.environment==='DATA'?snapshot.observations.filter(item=>item.symbol.startsWith('US.UST.')).slice(-6):[];return <>
  {stale&&<div className="stale-banner"><b>STALE DEMO SNAPSHOT</b><span>Last API update {formatTimestamp(data.generated_at)}. Values remain visible and explicitly stale.</span></div>}
  <section className="pulse"><div className="pulse-title">PAKISTAN MARKET PULSE <StatusBadge status="DEMO"/></div>{data.rates.slice(0,3).map(rate=><div key={rate.instrument}><b>{rate.instrument}</b><em className={rate.move_bp<0?'positive':'negative'}>{formatBasisPoints(rate.move_bp)}</em></div>)}{data.global_markets.slice(1,4).map(item=><div key={item.symbol}><b>{item.label}</b><MarketChange value={item.move} unit={item.move_unit==='bp'?' bp':'%'}/></div>)}</section>
  <div className="workspace-grid">
    <Panel title="Pakistan Market Pulse" eyebrow="DEMO · SYNTHETIC FIXTURE" actions={<FactBadge type="FACT"/>} className="market-panel"><div className="metrics"><div><label>POLICY RATE</label><strong>12.00%</strong><small>DEMO · UNCHANGED</small></div><div><label>3M MTB</label><strong>{formatYield(data.rates[0].yield_percent)}</strong><span className="positive">{formatBasisPoints(data.rates[0].move_bp)}</span></div><div><label>USD / PKR</label><strong>{data.global_markets.at(-1)?.display}</strong><small>DEMO · FLAT</small></div><div><label>10Y PIB</label><strong>{formatYield(data.rates.at(-1)?.yield_percent)}</strong><span className="positive">{formatBasisPoints(data.rates.at(-1)?.move_bp)}</span></div></div><div className="analysis"><FactBadge type="ARGUS VIEW"/><p>Illustrative workstation commentary only. Front-end fixture yields are lower while the synthetic long end is mixed.</p></div><SourceDisclosure source={data.fixture_source} observed={formatTimestamp(data.generated_at)}/></Panel>
    {official.length?<Panel title="U.S. Treasury Par Yield Curve" eyebrow="OFFICIAL · EOD · NOT LIVE" actions={<StatusBadge status={official.some(item=>item.freshness==='STALE')?'STALE':'OFFICIAL'}/>} className="global-panel"><table><thead><tr><th>TENOR</th><th>YIELD</th><th>STATE</th></tr></thead><tbody>{official.map(item=><tr key={item.symbol}><th>{item.symbol.split('.').at(-1)}</th><td>{formatYield(item.value)}</td><td>{item.freshness}</td></tr>)}</tbody></table><SourceDisclosure source={official[0].source} observed={official[0].observation_date??'Date unavailable'}/></Panel>:<Panel title="Global Markets Strip" eyebrow="DEMO · CROSS-ASSET" actions={<StatusBadge status={stale?'STALE':'DEMO'}/>} className="global-panel"><table><thead><tr><th>MARKET</th><th>LEVEL</th><th>MOVE</th></tr></thead><tbody>{data.global_markets.map(item=><tr key={item.symbol}><th>{item.label}</th><td>{item.display}</td><td><MarketChange value={item.move} unit={item.move_unit==='bp'?' bp':item.move_unit==='flat'?'':'%'}/></td></tr>)}</tbody></table><SourceDisclosure source={data.fixture_source} observed="Illustrative only"/></Panel>}
    <Panel title="Pakistan Government Rates" eyebrow="DEMO · YIELD MONITOR" actions={<><FactBadge type="FACT"/> <StatusBadge status="DEMO"/></>} className="rates-panel"><table><thead><tr><th>INSTRUMENT</th><th>TENOR</th><th>YIELD</th><th>1D MOVE</th><th>PREVIOUS</th><th>STATE</th></tr></thead><tbody>{data.rates.map(rate=><tr key={rate.instrument}><th>{rate.instrument}</th><td>{rate.tenor}</td><td>{formatYield(rate.yield_percent)}</td><td className={rate.move_bp<0?'positive':'negative'}>{formatBasisPoints(rate.move_bp)}</td><td>{formatYield(rate.previous_yield_percent)}</td><td><StatusBadge status={stale?'STALE':'DEMO'}/></td></tr>)}</tbody></table><SourceDisclosure source={data.fixture_source} observed={formatTimestamp(data.generated_at)}/></Panel>
    <Panel title="Pakistan Sovereign Curve" eyebrow="DEMO · DISPLAYED POINTS" actions={<FactBadge type="CALCULATED"/>} className="curve-panel"><div className="chart-wrap"><ResponsiveContainer width="100%" height="100%"><LineChart data={curve} margin={{top:12,right:18,bottom:0,left:-12}}><XAxis dataKey="tenor" tick={{fill:'#7f939f',fontSize:10}} axisLine={{stroke:'#243743'}}/><YAxis domain={[11.4,12.4]} tick={{fill:'#7f939f',fontSize:10}} tickFormatter={value=>`${value.toFixed(1)}%`} axisLine={false}/><Tooltip contentStyle={{background:'#14232c',border:'1px solid #38505e'}} formatter={value=>formatYield(Number(value))}/><Line dataKey="yield" stroke="#58b9c6" strokeWidth={2} dot={{fill:'#071015',stroke:'#58b9c6',strokeWidth:2,r:3}} isAnimationActive={false}/></LineChart></ResponsiveContainer></div><div className="curve-foot"><FactBadge type="CALCULATED"/><span>10Y minus 3M from displayed DEMO points</span><b>{formatBasisPoints(spread)}</b></div><SourceDisclosure source="ARGUS calculation on DEMO fixture" observed="Illustrative only"/></Panel>
    <Panel title="Events" eyebrow="DEMO · FORWARD CALENDAR" actions={<span className="updated">{data.events.length} ITEMS</span>} className="events-panel">{data.events.length?data.events.map(event=><div className="event-row" key={event.time+event.event}><time>{event.time}</time><span>{event.region}</span><b>{event.event}</b><em className={event.importance.toLowerCase()}>{event.importance}</em></div>):<EmptyState/>}<SourceDisclosure source={data.fixture_source} observed="Illustrative only"/></Panel>
    <Panel title="Source Health" eyebrow="DEMO · LOCAL API" actions={<span className="updated">NO EXTERNAL CALLS</span>} className="health-panel">{data.source_health.map(source=><div className="health-row" key={source.source}><i className={source.status==='READY'?'ok':''}/><div><b>{source.source}</b><small>{source.detail}</small></div><span>{source.status}</span></div>)}<div className="health-note"><FactBadge type="FACT"/><p>Health describes local fixtures and disabled connectors, not publisher availability.</p></div></Panel>
  </div></>}
