import {useEffect,useState} from 'react'; import {Line,LineChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {FactBadge,MarketChange,Panel,SourceDisclosure,StatusBadge} from '@argus/design-system';
import {formatBasisPoints,formatYield} from '@argus/financial-formatting';

const rates=[['3M MTB',11.82,-3.2,11.79],['6M MTB',11.74,-2.1,11.72],['12M MTB',11.55,-4.8,11.51],['3Y PIB',11.69,1.5,11.75],['5Y PIB',11.91,2.7,11.96],['10Y PIB',12.24,-1.3,12.31]] as const;
const curve=rates.map(([tenor,yieldValue])=>({tenor:tenor.split(' ')[0],yield:yieldValue}));
const global=[['S&P 500','5,412.18',0.42],['US 10Y','4.21%',-0.04],['DXY','103.84',-0.18],['BRENT','82.14',0.76],['GOLD','2,326.40',0.31],['USD/PKR','278.35',0.00]] as const;
const nav=['Overview','Pakistan Rates','Global Markets','Macro & Events','News & Research','Analytics Lab','Workspaces'];
function Logo(){return <div className="brand"><span className="mark">A</span><div><b>ARGUS</b><small>MARKETS WORKSTATION</small></div></div>}
function CommandPalette({close}:{close:()=>void}){return <div className="palette-wrap" onMouseDown={close}><div className="palette" role="dialog" aria-modal="true" aria-label="Command palette" onMouseDown={e=>e.stopPropagation()}><div className="palette-input"><span>⌕</span><input autoFocus placeholder="Search instruments, functions, or workspaces…"/><kbd>ESC</kbd></div><div className="palette-section">QUICK ACTIONS</div>{['Open Pakistan Rates','Inspect sovereign curve','Go to Source Health','Create workspace'].map((x,i)=><button key={x}><span>{x}</span><kbd>0{i+1}</kbd></button>)}</div></div>}
export function App(){const [palette,setPalette]=useState(false);useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setPalette(true)}if(e.key==='Escape')setPalette(false)};addEventListener('keydown',key);return()=>removeEventListener('keydown',key)},[]);return <div className="app">
  <header className="topbar"><Logo/><button className="search" onClick={()=>setPalette(true)}><span>⌕</span><span>Search markets or run a command</span><kbd>CTRL K</kbd></button><div className="sessions"><span><i className="open"/>PSX CLOSED</span><span><i className="open"/>LONDON OPEN</span><span><i/>US PRE</span></div><div className="clock"><small>DEMO SESSION</small><b>14:32 UTC</b></div></header>
  <aside><div className="nav-label">WORKSTATION</div>{nav.map((item,i)=><button className={i===0?'active':''} key={item}><span className="nav-icon">{['⌂','⌁','◎','▦','≡','ƒ','▤'][i]}</span>{item}{i===0&&<span className="active-dot"/>}</button>)}<div className="nav-label lower">SYSTEM</div><button><span className="nav-icon">◉</span>Source Health</button><button><span className="nav-icon">⚙</span>Settings</button><div className="sidebar-foot"><StatusBadge status="DEMO"/><span>Fixture environment<br/>No live market data</span></div></aside>
  <main><div className="workspace-head"><div><div className="breadcrumb">WORKSPACES / <b>HOME</b></div><h1>Market Monitor</h1></div><div className="workspace-actions"><button>▦ Default layout</button><button>＋ Add panel</button><button>•••</button></div></div>
    <div className="demo-banner"><b>DEMO ENVIRONMENT</b><span>All values are fictional fixtures for interface evaluation. Not live, official, or investment information.</span><StatusBadge status="DEMO"/></div>
    <section className="pulse"><div className="pulse-title">MARKET PULSE <span>DEMO</span></div><div><b>PAK RATES</b><em className="positive">▼ YIELDS</em></div><div><b>PKR</b><em>→ STABLE</em></div><div><b>KSE 100</b><em className="negative">▼ -0.40%</em></div><div><b>US 10Y</b><em className="positive">▼ -4.0 bp</em></div><div><b>BRENT</b><em className="positive">▲ +0.76%</em></div><div><b>DXY</b><em className="negative">▼ -0.18%</em></div></section>
    <div className="workspace-grid">
      <Panel title="Pakistan Market Pulse" eyebrow="DEMO · FACT" actions={<FactBadge type="FACT"/>} className="market-panel"><div className="metrics"><div><label>POLICY RATE</label><strong>12.00%</strong><small>Unchanged</small></div><div><label>KSE 100</label><strong>78,316</strong><MarketChange value={-0.4} unit="%"/></div><div><label>USD / PKR</label><strong>278.35</strong><MarketChange value={0}/></div><div><label>CPI YoY</label><strong>11.80%</strong><small>Previous 12.4%</small></div></div><div className="read"><FactBadge type="ARGUS VIEW"/><p>Demo narrative: front-end yields eased while longer tenors remained range-bound. This text is illustrative analysis, not factual market commentary.</p></div><SourceDisclosure source="ARGUS static fixtures · DEMO" observed="Illustrative only"/></Panel>
      <Panel title="Global Markets" eyebrow="DEMO · CROSS-ASSET" actions={<span className="updated">UPDATED 14:30 UTC</span>} className="global-panel"><table><tbody>{global.map(([name,value,change])=><tr key={name}><th>{name}</th><td>{value}</td><td><MarketChange value={change} unit={name==='US 10Y'?' bp':'%'}/></td></tr>)}</tbody></table><SourceDisclosure source="ARGUS static fixtures · DEMO" observed="Illustrative only"/></Panel>
      <Panel title="Pakistan Government Rates" eyebrow="DEMO · SECONDARY MARKET" actions={<><FactBadge type="FACT"/> <StatusBadge status="DEMO"/></>} className="rates-panel"><table><thead><tr><th>INSTRUMENT</th><th>YIELD</th><th>1D</th><th>PREV</th><th>STATUS</th></tr></thead><tbody>{rates.map(([name,yieldValue,change,prev])=><tr key={name}><th>{name}</th><td>{formatYield(yieldValue)}</td><td className={change<0?'positive':'negative'}>{formatBasisPoints(change)}</td><td>{formatYield(prev)}</td><td><span className="official">DEMO</span></td></tr>)}</tbody></table><SourceDisclosure source="ARGUS static fixtures · not an official source" observed="Illustrative only"/></Panel>
      <Panel title="Pakistan Sovereign Yield Curve" eyebrow="DEMO · INDICATIVE" actions={<><button className="mini active">CURRENT</button><button className="mini">1W</button><button className="mini">1M</button></>} className="curve-panel"><div className="chart-wrap"><ResponsiveContainer width="100%" height="100%"><LineChart data={curve} margin={{top:12,right:18,bottom:0,left:-12}}><XAxis dataKey="tenor" tick={{fill:'#7f939f',fontSize:10}} axisLine={{stroke:'#243743'}}/><YAxis domain={[11.4,12.4]} tick={{fill:'#7f939f',fontSize:10}} tickFormatter={v=>`${v.toFixed(1)}%`} axisLine={false}/><Tooltip contentStyle={{background:'#14232c',border:'1px solid #38505e'}} formatter={(v)=>formatYield(Number(v))}/><Line dataKey="yield" stroke="#58b9c6" strokeWidth={2} dot={{fill:'#071015',stroke:'#58b9c6',strokeWidth:2,r:3}} isAnimationActive={false}/></LineChart></ResponsiveContainer></div><div className="curve-foot"><FactBadge type="CALCULATED"/><span>Curve shape from displayed DEMO points</span><b>10Y–3M&nbsp; {formatBasisPoints((12.24-11.82)*100)}</b></div></Panel>
      <Panel title="Source Health" eyebrow="DEMO · SYSTEM STATUS" actions={<span className="updated">4 FIXTURE SOURCES</span>} className="health-panel">{[['Pakistan rates fixture','READY','Static'],['Global markets fixture','READY','Static'],['Market narrative fixture','READY','Static'],['External providers','DISABLED','Phase 1']].map(([name,status,note])=><div className="health-row" key={name}><i className={status==='READY'?'ok':''}/><div><b>{name}</b><small>{note}</small></div><span>{status}</span></div>)}<div className="health-note"><b>NO EXTERNAL CALLS</b><p>Provider adapters and ingestion are intentionally out of scope.</p></div></Panel>
    </div>
  </main>{palette&&<CommandPalette close={()=>setPalette(false)}/>}</div>}
